[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1"
anyhow = "1.0"
bytemuck = { version = "1.10", features = ["derive"] }
glam = { version = "0.24", features = ["bytemuck"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
winit = { version = "0.29", default-features = false, features = ["x11", "rwh_06"] }

renderer = { path = "../renderer" }
