[package]
name = "tron"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.10", features = ["derive"] }
env_logger = "0.9.0"
gltf = { version = "1", default-features = false, features = ["utils", "import", "names"] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
log = "0.4"
nalgebra-glm = { version = "0.17", features = ["convert-bytemuck"] }
pollster = "0.2.5"
range-alloc = "0.1"
thiserror = "1.0"
wgpu = "0.13.1"
winit = "0.27.1"
