[package]
name = "tron"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.9.1", features = ["derive"] }
env_logger = "0.9.0"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
log = "0.4.16"
nalgebra-glm = "0.17.0"
pollster = "0.2.5"
thiserror = "1.0.31"
wgpu = "0.12.0"
winit = "0.26.1"
