[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
anyhow = "1.0"
bytemuck = "1.0"
glam = "0.25"
indexmap = "2.1"
once_cell = "1.19"
profiling = "1.0"
range-alloc = "0.1"
shaderc = "0.8"
thiserror = "1.0"
tracing = "0.1"
vulkanalia = { version = "0.22", features = ["window", "libloading"] }
winit = { version = "0.29", default-features = false, features = ["x11", "rwh_06"] }

gfx = { path = "../gfx" }
shared = { path = "../shared" }

[features]
link-shaderc = ["shaderc/build-from-source"]
