[package]
name = "spirv"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["visit"] }
naga = { version = "0.13", features = ["wgsl-in", "spv-out"] }
